# Exercises



1. Write a function that determines whether a given numeric list
is a palindrome.

2. Write a function that reverses the order of elements in a given numeric list.

28. Write a function that determines if all elements in a given logical
list are equal to `True`.

29. Write a function that determines if any element in a given logical
list is equal to `True`.

30. Write a function that counts the number of elements equal to `True`
in a given logical list.

24. Write a function that computes the cumulative sums of consecutive elements
in a given numeric `x`, i.e., a vector `r` with $r_i = \sum_{j=1}^i x_j$.

25. Write a funciton to compute the iterated (adjacent)
difference between consecutive elements
in a given numeric list `x`, i.e., a vector `r` with $r_i = x_{i+1}-x_i$.

23. Write a function that adds the corresponding items
in two numeric lists (elementwise), i.e., for given `x`, `y` return
`r` such that $r_i=x_i+y_i$. If vectors are of unequal lenghts,
the shorter one should be recycled, e.g.,
`[1,2,3,4,5,6]+[7,8]==[1,2,3,4,5,6]+[7,8,7,8,7,8]`.

26. Write a function that determines if a given list is sorted non-decreasingly.

2. Write a function which checks if a given natural number
is prime.

3. Write a function that counts the number of primes in the set 
$\{a,a+1,\dots,b\}$, for given $a<b$. Calling the function from the above
exercise does not lead to a time-optimal solution.
Hint: implement the Eratosthenes sieve.

4. Write a function that determines the least and the greatest element
in a given numeric list. Only one `for` loop is allowed.

4. Write a function that determines the indexes (positions)
of the least and the greatest element in a given numeric list.

5. Write a function which finds the 3rd least element in a given numeric
list, e.g., given `[3.0,5.0,2.0,4.0,1.0,6.0]`, the result should be equal to `4.0`.
Only a single `for` loop is allowed.

6. Write a function which finds the $k$ (given) least elements in some
on-line data stream (it can be based on a list, but you are allowed
to inspect each its element only once). 

7. Let `t` be an integer list with elements from 0 to $k-1$ for some $k$
(if your language - e.g., R - supports $1$-based indexing, assume that the elements
are from 1 to $k$).
Write a function that determines the mode, i.e, the most frequently occurring
value in `t`. If a mode is not-unique, return a random one.
Hint: use an auxiliary list of length $k$ to count the number of occurrences
of each element.

8. Let `t` and $k$ be as above. Implement the bucket sort algorithm.
Hint: the same as above.

14. Let `x` - numeric vector, `t` - an integer list with elements from 0 to $k-1$ for some $k$.
Return a vector of length $k$ which gives arithmetic means of observations in `x` grouped by 
corresponding values in `t` (something like SELECT t, MEAN(x) GROUP BY t).

15. The same, but compute the group medians.

9. Write a function to determine the mode in a sequence of arbitrary
(assume that they are immutable/hashable) objects. Hint: use a dictionary.

27. Write a function that determines if all elements in a given list are unique.
Use a dictionary.

10. Let $w(x)=w_0+w_1 x+\dots+w_n x^n$ and $v(x)=v_0+v_1 x+v_m x^m$ be two polynomials
of degrees $n$ and $m$, respectively.
Write a function takes takes two lists of coefficients, one of length $n+1$ and the
other of length $m+1$, representing two polynomials $w$ and $v$. 
Return a list of coefficients that represent the
polynomial $u(x)=w(x)v(x)$.

12. Implement the selection sort algorithm.

13. Implement the insertion sort algorithm.

14. Let `x` be a non-decreasingly sorted integer list.
Write a function that verifies whether a given `v` is in `x`.
Implement an algorithm that has a logarithmic time complexity.

15. Write a function that determines if all elements in a given sorted
list are unique.

11. Let `x` and `y` be two non-decreasingly sorted integer lists.
Write a function that returns their non-decreasingly sorted concatenation,
e.g., if `x=[1,4,5]` and `y=[0,2,3,6]`, then the expected output is `[0,1,2,3,4,5,6]`.
Implement an algorithm that has linear time complexity.

12. Let `x` and `y` be two (strictly) increasingly sorted integer lists,
representing two subsets of $\mathbb{Z}$.
Write a function that determines their union.

13. As above, but now implement the set intersection.

15. Implement the merge sort algorithm.

16. Write a function that rearranges the elements in a numeric list in such a way
that the elements less than or equal to a given `v` are followed by the elements
greater than `v`.

17. Implement the quick sort algorithm (with random pivoting).

18. Implement a hybrid quick sort algorithm:
in a recursive function call, if a subsequence of length ≤ 20 is to be ordered, 
then the insertion sort algorithm is used instead of the plain quick sort scheme.
Note: hybrid quick sort tends to be faster than its plain version.

19. Write a function that randomly rearranges the elements in a given
numeric list (generates its random permutation).
Implement the Knuth-Fisher-Yates shuffle. 

20. Implement the quick-select algorithm for finding the $k$-th smallest
value in an unsorted list (for a given $k$).

21. Implement a partial quick sort  algorithm that guarantes
that the $k$ smallest values are in order  (for a given $k$).

22. Implement an algorithm that determines the permutation of elements
that generates a non-decreasingly ordered version of a given list `x`
(compare `argsort()` in NumPy or `order()` in R),
i.e., an integer list $[i_1,i_2,\dots,i_n]$ such that $x_{i_1}\le x_{i_2}\le\dots\le x_{i_n}$.
The routine should be based on a stable sorting algorithm,
i.e., if $x_{i_u}=x_{i_v}$ for some $u<v$, then necessarily $i_u<i_v$
(the relative ordering of elements with the same key should be preserved).

23. Given two integer lists of arbitrary lenghts, determine if the
first one is lexicographically less-than-or-equal-to the second one.

24. Write a function that ranks each element in a given numeric vector.
For example, given (1, 3, 5, 2, 4, 3), we should get
(1.0, 3.5, 6.0, 2.0, 5.0, 3.5).

25. Four men want to cross a bridge. But at most 2 people may cross it at a time.
For man A it takes 10 minutes to cross, for B -- 5 minutes,
C -- 2 minutes, and D  -- 1 minute. If two people cross the bridge together,
they must walk at the pace of the slower one.
Also, it is night. Each trip requires a flashlight.  There
is only one flashlight. The men are not allowed to toss the light over
the river. How fast can you get all 4 men over the bridge?
Examine all the 108 possible solutions and determine the optimal one
(the optimal time is $<19$).

In [65]:
%load_ext Cython

The Cython extension is already loaded. To reload it, use:
  %reload_ext Cython


## 1. Write a function that determines whether a given numeric list is a palindrome

In [229]:
%%cython 
def palindrome(listy):
    res = True
    i=0
    while True & (i<=len(listy)//2):
        res = res & (listy[i] == listy[-i-1])
        i+=1
    return res


In [230]:
%%cython
import numpy as np
cimport numpy as np
from cpython cimport bool
cpdef cpalindrome(np.ndarray[np.int64_t] listy):
    cdef bool res = True
    cdef int i = 0
    cdef int lengthy = listy.size//2
    cdef int remainder = listy.size%2
    cdef np.ndarray[np.int64_t] list1 = listy[:lengthy]
    cdef np.ndarray[np.int64_t] list2 = listy[remainder+lengthy:]
    list2 = list2[::-1]
    return np.array_equal(list1,list2)

In [231]:
l = np.array([1,2,3,4,5,4,3,2,1])

print(palindrome(l))
print(cpalindrome(l))

True
True


In [232]:
l1 = np.random.randint(1,100,10**7)
l2 = l1[::-1]
l = np.append(l1,l2)

%timeit palindrome(l)
%timeit cpalindrome(l)

1 loop, best of 3: 2.63 s per loop
100 loops, best of 3: 13.6 ms per loop


## 2. Write a function that reverses the order of elements in a given numeric list.

In [252]:
%%cython
import numpy as np
def invert(listy):
    """ This function reverses the order of elements of a list"""
    lengthy = len(listy)
    listz = np.empty(lengthy)
    for i in np.arange(lengthy):
        listz[-i-1] = listy[i]
    return(listz)

In [258]:
%%cython
import numpy as np
cimport numpy as np
from cpython cimport bool
cpdef cinvert(np.ndarray[np.int64_t] listy):
    """ This function reverses the order of elements of a list"""
    cdef int lengthy = listy.size
    cdef int i = 0
    cdef np.ndarray[np.double_t] listz = np.empty(lengthy)
    for i in np.arange(lengthy):
        np.append(listz,listy[i])
    #for i in np.arange(lengthy):
    #    listz[-i-1] = listy[i]
    return(listz)

In [259]:
l = np.random.randint(1,5,10)
print(l[::-1])
print(invert(l))
print(cinvert(l))

[1 4 3 1 1 2 1 2 1 2]
[ 1.  4.  3.  1.  1.  2.  1.  2.  1.  2.]
[ 1.  4.  3.  1.  1.  2.  1.  2.  1.  2.]


In [260]:
l = np.random.randint(1,100,10**7)

%timeit palindrome(l)
%timeit cpalindrome(l)

1 loop, best of 3: 1.25 s per loop
100 loops, best of 3: 6.6 ms per loop
