In [1]:
sc

In [2]:
from pyspark.sql import SQLContext
sqlc = SQLContext(sc)

## Summary Statistics

In [3]:
from pyspark.mllib.linalg import Vectors, Vector
from pyspark.mllib.stat import Statistics

In [4]:
observations = sc.parallelize([Vectors.dense(2.0,1.0),
                               Vectors.dense(9.0,3.0),
                               Vectors.dense(-7.0,5.0)])

In [7]:
summary = Statistics.colStats(observations)

In [8]:
summary.mean()

array([ 1.33333333,  3.        ])

In [9]:
summary.variance()

array([ 64.33333333,   4.        ])

In [10]:
summary.numNonzeros()

array([ 3.,  3.])

In [11]:
summary.normL1()

array([ 18.,   9.])

In [12]:
summary.normL2()

array([ 11.5758369 ,   5.91607978])

In [13]:
X = observations.map(lambda obs: obs[0])
Y = observations.map(lambda obs: obs[1])

In [19]:
Statistics.corr(X, Y, "pearson")

-0.5610408535732833

In [20]:
Statistics.corr(observations, method="pearson")

array([[ 1.        , -0.56104085],
       [-0.56104085,  1.        ]])

## Random RDDs

In [21]:
from pyspark.mllib.random import RandomRDDs

In [23]:
million = RandomRDDs.poissonRDD(sc, mean=1.0, size=1000000, numPartitions=10)
million.take(10)

[1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 2.0, 0.0, 1.0, 3.0]

In [24]:
million.mean()

0.9977700000000016

In [25]:
million.variance()

0.9977830271

In [26]:
data = RandomRDDs.normalVectorRDD(sc, numRows=10000, numCols=3, numPartitions=10)

In [27]:
data.take(1)

[array([ 0.02664613, -1.19385032,  0.37903009])]

In [32]:
stats = Statistics.colStats(data)

In [33]:
stats.mean()

array([-0.00557426, -0.00427579, -0.00394252])

In [34]:
stats.variance()

array([ 1.00298755,  0.97480557,  0.98141385])

In [35]:
stats.numNonzeros()

array([ 10000.,  10000.,  10000.])

In [36]:
stats.normL1()

array([ 7972.55214735,  7822.22326854,  7897.78371531])

In [37]:
stats.normL2()

array([ 100.14580978,   98.72823159,   99.06216476])